#!/usr/bin/env python

#   reconnect_mullvad_every_n_seconds [seconds to wait]

#     v0.2 July 1st '24 by d@v1d.dk
#
# Starts a timer to reconnect Mullvad:
#
#   reconnect_mullvad_every_n_seconds [seconds to wait]
#
# CTRL-C (once) reconnects now and restarts timer.
# Ctrl-C (twice) to quit.



import time, sh, sys
from progress.bar import FillingSquaresBar as Bar

if len(sys.argv) == 1:
    print("please supply default argument: time to wait in seconds")
    sys.exit()
time_in_secs = int(sys.argv[1])
time_in_minutes = int(time_in_secs/60)

while True:
    bar = Bar(f'Waiting {time_in_minutes} minutes', max=time_in_secs)
    for i in range(time_in_secs):
        try:
            time.sleep(1)
            bar.next()
        except KeyboardInterrupt:
            try:
                time.sleep(0.5)
                break # breaks for loop (only), finishes while loop
            except KeyboardInterrupt:
                print(f"\nexiting... \nthank you for using {sys.argv[0][2:]}")
                sys.exit()
    print("\nreconnecting Mullvad...")
    sh.mullvad("reconnect")
    time.sleep(5)
    response = sh.mullvad("status")
    print(response)

