#!/usr/bin/env python

#   reconnect_mullvad_every_n_seconds
#     v0.3 July 1st '24 by d@v1d.dk

import time, sh, sys, re
from progress.bar import FillingSquaresBar as Bar
import random, argparse

description = """Waits for n minutes and then changes Mullvad IP, optionally also country. 
                 Ctrl-C to change now and restart timer, Ctrl-C twice to exit."""
parser = argparse.ArgumentParser(description=description)
parser.add_argument("time_in_minutes", help="time to wait in minutes")
parser.add_argument("-c", "--countries", help="a string of 2-character country codes to randomly alternate between")
args = parser.parse_args()

time_in_minutes = int(args.time_in_minutes)
time_in_secs = time_in_minutes * 60


filename = sys.argv[0].split("/")[-1]
while True:
    mullvad_status = sh.mullvad("status")
    print(mullvad_status)
    m = re.findall('Connect...? to (\w\w)', mullvad_status)
    current_country = set(m[0]) 
    if time_in_minutes > 1:
        bar = Bar(f'Waiting {time_in_minutes} minutes', max=time_in_secs)
    else:
        bar = Bar(f'Waiting {time_in_minutes} minute', max=time_in_secs)
    for i in range(time_in_secs):
        try:
            time.sleep(1)
            bar.next()
        except KeyboardInterrupt:
            try:
                time.sleep(0.5)
                break # breaks for loop (only), finishes while loop
            except KeyboardInterrupt:
                print(f"\nexiting... \nthank you for using {filename}")
                sys.exit()
    print("\nreconnecting Mullvad...")
    if not args.countries:    
        sh.mullvad("reconnect")
        time.sleep(2)
        response = sh.mullvad("status")
        #print(response)
    else:
        countries = set(args.countries.split())
        countries_wo_current = list(countries - current_country)
        rand_country = random.choice(countries_wo_current)
        sh.mulocation(rand_country)
        try:
            time.sleep(2)
        except KeyboardInterrupt:
            print(f"\nexiting... \nthank you for using {filename}")
            sys.exit()


